params_name_conversion = {
#'global_step:0',
 'resnet50/conv2d/kernel:0': 'backbone.conv1.weight',
 'resnet50/batch_normalization/gamma:0': 'backbone.bn1.weight',
 'resnet50/batch_normalization/beta:0': 'backbone.bn1.bias',
 'resnet50/batch_normalization/moving_mean:0': 'backbone.bn1.running_mean',
 'resnet50/batch_normalization/moving_variance:0': 'backbone.bn1.running_var',
 
 # the block one of the Resnet50
 'resnet50/conv2d_1/kernel:0': 'backbone.layer1.0.downsample.0.weight',
 'resnet50/batch_normalization_1/gamma:0': 'backbone.layer1.0.downsample.1.weight',
 'resnet50/batch_normalization_1/beta:0': 'backbone.layer1.0.downsample.1.bias',
 'resnet50/batch_normalization_1/moving_mean:0': 'backbone.layer1.0.downsample.1.running_mean',
 'resnet50/batch_normalization_1/moving_variance:0': 'backbone.layer1.0.downsample.1.running_var',
 'resnet50/conv2d_2/kernel:0': 'backbone.layer1.0.conv1.weight',
 'resnet50/batch_normalization_2/gamma:0': 'backbone.layer1.0.bn1.weight',
 'resnet50/batch_normalization_2/beta:0': 'backbone.layer1.0.bn1.bias',
 'resnet50/batch_normalization_2/moving_mean:0': 'backbone.layer1.0.bn1.running_mean',
 'resnet50/batch_normalization_2/moving_variance:0': 'backbone.layer1.0.bn1.running_var',
 'resnet50/conv2d_3/kernel:0': 'backbone.layer1.0.conv2.weight',
 'resnet50/batch_normalization_3/gamma:0': 'backbone.layer1.0.bn2.weight',
 'resnet50/batch_normalization_3/beta:0': 'backbone.layer1.0.bn2.bias',
 'resnet50/batch_normalization_3/moving_mean:0': 'backbone.layer1.0.bn2.running_mean',
 'resnet50/batch_normalization_3/moving_variance:0' : 'backbone.layer1.0.bn2.running_var',
 'resnet50/conv2d_4/kernel:0': 'backbone.layer1.0.conv3.weight',
 'resnet50/batch_normalization_4/gamma:0': 'backbone.layer1.0.bn3.weight',
 'resnet50/batch_normalization_4/beta:0': 'backbone.layer1.0.bn3.bias',
 'resnet50/batch_normalization_4/moving_mean:0': 'backbone.layer1.0.bn3.running_mean',
 'resnet50/batch_normalization_4/moving_variance:0': 'backbone.layer1.0.bn3.running_var',
 
 'resnet50/conv2d_5/kernel:0': 'backbone.layer1.1.conv1.weight',
 'resnet50/batch_normalization_5/gamma:0': 'backbone.layer1.1.bn1.weight',
 'resnet50/batch_normalization_5/beta:0': 'backbone.layer1.1.bn1.bias',
 'resnet50/batch_normalization_5/moving_mean:0': 'backbone.layer1.1.bn1.running_mean',
 'resnet50/batch_normalization_5/moving_variance:0': 'backbone.layer1.1.bn1.running_var',
 'resnet50/conv2d_6/kernel:0': 'backbone.layer1.1.conv2.weight',
 'resnet50/batch_normalization_6/gamma:0': 'backbone.layer1.1.bn2.weight',
 'resnet50/batch_normalization_6/beta:0': 'backbone.layer1.1.bn2.bias',
 'resnet50/batch_normalization_6/moving_mean:0': 'backbone.layer1.1.bn2.running_mean',
 'resnet50/batch_normalization_6/moving_variance:0': 'backbone.layer1.1.bn2.running_var',
 'resnet50/conv2d_7/kernel:0': 'backbone.layer1.1.conv3.weight',
 'resnet50/batch_normalization_7/gamma:0': 'backbone.layer1.1.bn3.weight',
 'resnet50/batch_normalization_7/beta:0': 'backbone.layer1.1.bn3.bias',
 'resnet50/batch_normalization_7/moving_mean:0': 'backbone.layer1.1.bn3.running_mean',
 'resnet50/batch_normalization_7/moving_variance:0': 'backbone.layer1.1.bn3.running_var',
 'resnet50/conv2d_8/kernel:0': 'backbone.layer1.2.conv1.weight',
 'resnet50/batch_normalization_8/gamma:0': 'backbone.layer1.2.bn1.weight',
 'resnet50/batch_normalization_8/beta:0': 'backbone.layer1.2.bn1.bias',
 'resnet50/batch_normalization_8/moving_mean:0': 'backbone.layer1.2.bn1.running_mean',
 'resnet50/batch_normalization_8/moving_variance:0': 'backbone.layer1.2.bn1.running_var',
 'resnet50/conv2d_9/kernel:0': 'backbone.layer1.2.conv2.weight',
 'resnet50/batch_normalization_9/gamma:0': 'backbone.layer1.2.bn2.weight',
 'resnet50/batch_normalization_9/beta:0': 'backbone.layer1.2.bn2.bias',
 'resnet50/batch_normalization_9/moving_mean:0': 'backbone.layer1.2.bn2.running_mean',
 'resnet50/batch_normalization_9/moving_variance:0': 'backbone.layer1.2.bn2.running_var',
 'resnet50/conv2d_10/kernel:0': 'backbone.layer1.2.conv3.weight',
 'resnet50/batch_normalization_10/gamma:0': 'backbone.layer1.2.bn3.weight',
 'resnet50/batch_normalization_10/beta:0': 'backbone.layer1.2.bn3.bias',
 'resnet50/batch_normalization_10/moving_mean:0': 'backbone.layer1.2.bn3.running_mean',
 'resnet50/batch_normalization_10/moving_variance:0': 'backbone.layer1.2.bn3.running_var',
 
 # the second block of the Resnet50
 'resnet50/conv2d_11/kernel:0': 'backbone.layer2.0.downsample.0.weight',
 'resnet50/batch_normalization_11/gamma:0': 'backbone.layer2.0.downsample.1.weight',
 'resnet50/batch_normalization_11/beta:0': 'backbone.layer2.0.downsample.1.bias',
 'resnet50/batch_normalization_11/moving_mean:0': 'backbone.layer2.0.downsample.1.running_mean',
 'resnet50/batch_normalization_11/moving_variance:0': 'backbone.layer2.0.downsample.1.running_var',
 'resnet50/conv2d_12/kernel:0': 'backbone.layer2.0.conv1.weight',
 'resnet50/batch_normalization_12/gamma:0': 'backbone.layer2.0.bn1.weight',
 'resnet50/batch_normalization_12/beta:0': 'backbone.layer2.0.bn1.bias',
 'resnet50/batch_normalization_12/moving_mean:0': 'backbone.layer2.0.bn1.running_mean',
 'resnet50/batch_normalization_12/moving_variance:0': 'backbone.layer2.0.bn1.running_var',
 'resnet50/conv2d_13/kernel:0': 'backbone.layer2.0.conv2.weight',
 'resnet50/batch_normalization_13/gamma:0': 'backbone.layer2.0.bn2.weight',
 'resnet50/batch_normalization_13/beta:0': 'backbone.layer2.0.bn2.bias',
 'resnet50/batch_normalization_13/moving_mean:0': 'backbone.layer2.0.bn2.running_mean',
 'resnet50/batch_normalization_13/moving_variance:0': 'backbone.layer2.0.bn2.running_var',
 'resnet50/conv2d_14/kernel:0': 'backbone.layer2.0.conv3.weight',
 'resnet50/batch_normalization_14/gamma:0': 'backbone.layer2.0.bn3.weight',
 'resnet50/batch_normalization_14/beta:0': 'backbone.layer2.0.bn3.bias',
 'resnet50/batch_normalization_14/moving_mean:0': 'backbone.layer2.0.bn3.running_mean',
 'resnet50/batch_normalization_14/moving_variance:0': 'backbone.layer2.0.bn3.running_var',
 
 'resnet50/conv2d_15/kernel:0': 'backbone.layer2.1.conv1.weight',
 'resnet50/batch_normalization_15/gamma:0': 'backbone.layer2.1.bn1.weight',
 'resnet50/batch_normalization_15/beta:0': 'backbone.layer2.1.bn1.bias',
 'resnet50/batch_normalization_15/moving_mean:0': 'backbone.layer2.1.bn1.running_mean',
 'resnet50/batch_normalization_15/moving_variance:0': 'backbone.layer2.1.bn1.running_var',
 'resnet50/conv2d_16/kernel:0': 'backbone.layer2.1.conv2.weight',
 'resnet50/batch_normalization_16/gamma:0': 'backbone.layer2.1.bn2.weight',
 'resnet50/batch_normalization_16/beta:0': 'backbone.layer2.1.bn2.bias',
 'resnet50/batch_normalization_16/moving_mean:0': 'backbone.layer2.1.bn2.running_mean',
 'resnet50/batch_normalization_16/moving_variance:0': 'backbone.layer2.1.bn2.running_var',
 'resnet50/conv2d_17/kernel:0': 'backbone.layer2.1.conv3.weight',
 'resnet50/batch_normalization_17/gamma:0': 'backbone.layer2.1.bn3.weight',
 'resnet50/batch_normalization_17/beta:0': 'backbone.layer2.1.bn3.bias',
 'resnet50/batch_normalization_17/moving_mean:0': 'backbone.layer2.1.bn3.running_mean',
 'resnet50/batch_normalization_17/moving_variance:0': 'backbone.layer2.1.bn3.running_var',
 'resnet50/conv2d_18/kernel:0': 'backbone.layer2.2.conv1.weight',
 'resnet50/batch_normalization_18/gamma:0': 'backbone.layer2.2.bn1.weight',
 'resnet50/batch_normalization_18/beta:0': 'backbone.layer2.2.bn1.bias',
 'resnet50/batch_normalization_18/moving_mean:0': 'backbone.layer2.2.bn1.running_mean',
 'resnet50/batch_normalization_18/moving_variance:0': 'backbone.layer2.2.bn1.running_var',
 'resnet50/conv2d_19/kernel:0': 'backbone.layer2.2.conv2.weight',
 'resnet50/batch_normalization_19/gamma:0': 'backbone.layer2.2.bn2.weight',
 'resnet50/batch_normalization_19/beta:0': 'backbone.layer2.2.bn2.bias',
 'resnet50/batch_normalization_19/moving_mean:0': 'backbone.layer2.2.bn2.running_mean',
 'resnet50/batch_normalization_19/moving_variance:0': 'backbone.layer2.2.bn2.running_var',
 'resnet50/conv2d_20/kernel:0': 'backbone.layer2.2.conv3.weight',
 'resnet50/batch_normalization_20/gamma:0': 'backbone.layer2.2.bn3.weight',
 'resnet50/batch_normalization_20/beta:0': 'backbone.layer2.2.bn3.bias',
 'resnet50/batch_normalization_20/moving_mean:0': 'backbone.layer2.2.bn3.running_mean',
 'resnet50/batch_normalization_20/moving_variance:0': 'backbone.layer2.2.bn3.running_var',
 'resnet50/conv2d_21/kernel:0': 'backbone.layer2.3.conv1.weight',
 'resnet50/batch_normalization_21/gamma:0': 'backbone.layer2.3.bn1.weight',
 'resnet50/batch_normalization_21/beta:0': 'backbone.layer2.3.bn1.bias',
 'resnet50/batch_normalization_21/moving_mean:0': 'backbone.layer2.3.bn1.running_mean',
 'resnet50/batch_normalization_21/moving_variance:0': 'backbone.layer2.3.bn1.running_var',
 'resnet50/conv2d_22/kernel:0': 'backbone.layer2.3.conv2.weight',
 'resnet50/batch_normalization_22/gamma:0': 'backbone.layer2.3.bn2.weight',
 'resnet50/batch_normalization_22/beta:0': 'backbone.layer2.3.bn2.bias',
 'resnet50/batch_normalization_22/moving_mean:0': 'backbone.layer2.3.bn2.running_mean',
 'resnet50/batch_normalization_22/moving_variance:0': 'backbone.layer2.3.bn2.running_var',
 'resnet50/conv2d_23/kernel:0': 'backbone.layer2.3.conv3.weight',
 'resnet50/batch_normalization_23/gamma:0': 'backbone.layer2.3.bn3.weight',
 'resnet50/batch_normalization_23/beta:0': 'backbone.layer2.3.bn3.bias',
 'resnet50/batch_normalization_23/moving_mean:0': 'backbone.layer2.3.bn3.running_mean',
 'resnet50/batch_normalization_23/moving_variance:0': 'backbone.layer2.3.bn3.running_var',
 
 
 # block 3 of the Resnet50
 'resnet50/conv2d_24/kernel:0': 'backbone.layer3.0.downsample.0.weight',
 'resnet50/batch_normalization_24/gamma:0': 'backbone.layer3.0.downsample.1.weight',
 'resnet50/batch_normalization_24/beta:0': 'backbone.layer3.0.downsample.1.bias',
 'resnet50/batch_normalization_24/moving_mean:0': 'backbone.layer3.0.downsample.1.running_mean',
 'resnet50/batch_normalization_24/moving_variance:0': 'backbone.layer3.0.downsample.1.running_var',
 'resnet50/conv2d_25/kernel:0': 'backbone.layer3.0.conv1.weight',
 'resnet50/batch_normalization_25/gamma:0': 'backbone.layer3.0.bn1.weight',
 'resnet50/batch_normalization_25/beta:0': 'backbone.layer3.0.bn1.bias',
 'resnet50/batch_normalization_25/moving_mean:0': 'backbone.layer3.0.bn1.running_mean',
 'resnet50/batch_normalization_25/moving_variance:0': 'backbone.layer3.0.bn1.running_var',
 'resnet50/conv2d_26/kernel:0': 'backbone.layer3.0.conv2.weight',
 'resnet50/batch_normalization_26/gamma:0': 'backbone.layer3.0.bn2.weight',
 'resnet50/batch_normalization_26/beta:0': 'backbone.layer3.0.bn2.bias',
 'resnet50/batch_normalization_26/moving_mean:0': 'backbone.layer3.0.bn2.running_mean',
 'resnet50/batch_normalization_26/moving_variance:0': 'backbone.layer3.0.bn2.running_var',
 'resnet50/conv2d_27/kernel:0': 'backbone.layer3.0.conv3.weight',
 'resnet50/batch_normalization_27/gamma:0': 'backbone.layer3.0.bn3.weight',
 'resnet50/batch_normalization_27/beta:0': 'backbone.layer3.0.bn3.bias',
 'resnet50/batch_normalization_27/moving_mean:0': 'backbone.layer3.0.bn3.running_mean',
 'resnet50/batch_normalization_27/moving_variance:0': 'backbone.layer3.0.bn3.running_var',
 
 'resnet50/conv2d_28/kernel:0': 'backbone.layer3.1.conv1.weight',
 'resnet50/batch_normalization_28/gamma:0': 'backbone.layer3.1.bn1.weight',
 'resnet50/batch_normalization_28/beta:0': 'backbone.layer3.1.bn1.bias',
 'resnet50/batch_normalization_28/moving_mean:0': 'backbone.layer3.1.bn1.running_mean',
 'resnet50/batch_normalization_28/moving_variance:0': 'backbone.layer3.1.bn1.running_var',
 'resnet50/conv2d_29/kernel:0': 'backbone.layer3.1.conv2.weight',
 'resnet50/batch_normalization_29/gamma:0': 'backbone.layer3.1.bn2.weight',
 'resnet50/batch_normalization_29/beta:0': 'backbone.layer3.1.bn2.bias',
 'resnet50/batch_normalization_29/moving_mean:0': 'backbone.layer3.1.bn2.running_mean',
 'resnet50/batch_normalization_29/moving_variance:0': 'backbone.layer3.1.bn2.running_var',
 'resnet50/conv2d_30/kernel:0': 'backbone.layer3.1.conv3.weight',
 'resnet50/batch_normalization_30/gamma:0': 'backbone.layer3.1.bn3.weight',
 'resnet50/batch_normalization_30/beta:0': 'backbone.layer3.1.bn3.bias',
 'resnet50/batch_normalization_30/moving_mean:0': 'backbone.layer3.1.bn3.running_mean',
 'resnet50/batch_normalization_30/moving_variance:0': 'backbone.layer3.1.bn3.running_var',
 
 'resnet50/conv2d_31/kernel:0': 'backbone.layer3.2.conv1.weight',
 'resnet50/batch_normalization_31/gamma:0': 'backbone.layer3.2.bn1.weight',
 'resnet50/batch_normalization_31/beta:0': 'backbone.layer3.2.bn1.bias',
 'resnet50/batch_normalization_31/moving_mean:0': 'backbone.layer3.2.bn1.running_mean',
 'resnet50/batch_normalization_31/moving_variance:0': 'backbone.layer3.2.bn1.running_var',
 'resnet50/conv2d_32/kernel:0': 'backbone.layer3.2.conv2.weight',
 'resnet50/batch_normalization_32/gamma:0': 'backbone.layer3.2.bn2.weight',
 'resnet50/batch_normalization_32/beta:0': 'backbone.layer3.2.bn2.bias',
 'resnet50/batch_normalization_32/moving_mean:0': 'backbone.layer3.2.bn2.running_mean',
 'resnet50/batch_normalization_32/moving_variance:0': 'backbone.layer3.2.bn2.running_var',
 'resnet50/conv2d_33/kernel:0': 'backbone.layer3.2.conv3.weight',
 'resnet50/batch_normalization_33/gamma:0': 'backbone.layer3.2.bn3.weight',
 'resnet50/batch_normalization_33/beta:0': 'backbone.layer3.2.bn3.bias',
 'resnet50/batch_normalization_33/moving_mean:0': 'backbone.layer3.2.bn3.running_mean',
 'resnet50/batch_normalization_33/moving_variance:0': 'backbone.layer3.2.bn3.running_var',
 
 'resnet50/conv2d_34/kernel:0': 'backbone.layer3.3.conv1.weight',
 'resnet50/batch_normalization_34/gamma:0': 'backbone.layer3.3.bn1.weight',
 'resnet50/batch_normalization_34/beta:0': 'backbone.layer3.3.bn1.bias',
 'resnet50/batch_normalization_34/moving_mean:0': 'backbone.layer3.3.bn1.running_mean',
 'resnet50/batch_normalization_34/moving_variance:0': 'backbone.layer3.3.bn1.running_var',
 'resnet50/conv2d_35/kernel:0': 'backbone.layer3.3.conv2.weight',
 'resnet50/batch_normalization_35/gamma:0': 'backbone.layer3.3.bn2.weight',
 'resnet50/batch_normalization_35/beta:0': 'backbone.layer3.3.bn2.bias',
 'resnet50/batch_normalization_35/moving_mean:0': 'backbone.layer3.3.bn2.running_mean',
 'resnet50/batch_normalization_35/moving_variance:0': 'backbone.layer3.3.bn2.running_var',
 'resnet50/conv2d_36/kernel:0': 'backbone.layer3.3.conv3.weight',
 'resnet50/batch_normalization_36/gamma:0': 'backbone.layer3.3.bn3.weight',
 'resnet50/batch_normalization_36/beta:0': 'backbone.layer3.3.bn3.bias',
 'resnet50/batch_normalization_36/moving_mean:0': 'backbone.layer3.3.bn3.running_mean',
 'resnet50/batch_normalization_36/moving_variance:0': 'backbone.layer3.3.bn3.running_var',
 
 'resnet50/conv2d_37/kernel:0': 'backbone.layer3.4.conv1.weight',
 'resnet50/batch_normalization_37/gamma:0': 'backbone.layer3.4.bn1.weight',
 'resnet50/batch_normalization_37/beta:0': 'backbone.layer3.4.bn1.bias',
 'resnet50/batch_normalization_37/moving_mean:0': 'backbone.layer3.4.bn1.running_mean',
 'resnet50/batch_normalization_37/moving_variance:0': 'backbone.layer3.4.bn1.running_var',
 'resnet50/conv2d_38/kernel:0': 'backbone.layer3.4.conv2.weight',
 'resnet50/batch_normalization_38/gamma:0': 'backbone.layer3.4.bn2.weight',
 'resnet50/batch_normalization_38/beta:0': 'backbone.layer3.4.bn2.bias',
 'resnet50/batch_normalization_38/moving_mean:0': 'backbone.layer3.4.bn2.running_mean',
 'resnet50/batch_normalization_38/moving_variance:0': 'backbone.layer3.4.bn2.running_var',
 'resnet50/conv2d_39/kernel:0': 'backbone.layer3.4.conv3.weight',
 'resnet50/batch_normalization_39/gamma:0': 'backbone.layer3.4.bn3.weight',
 'resnet50/batch_normalization_39/beta:0': 'backbone.layer3.4.bn3.bias',
 'resnet50/batch_normalization_39/moving_mean:0': 'backbone.layer3.4.bn3.running_mean',
 'resnet50/batch_normalization_39/moving_variance:0': 'backbone.layer3.4.bn3.running_var',
 
 'resnet50/conv2d_40/kernel:0': 'backbone.layer3.5.conv1.weight',
 'resnet50/batch_normalization_40/gamma:0': 'backbone.layer3.5.bn1.weight',
 'resnet50/batch_normalization_40/beta:0': 'backbone.layer3.5.bn1.bias',
 'resnet50/batch_normalization_40/moving_mean:0': 'backbone.layer3.5.bn1.running_mean',
 'resnet50/batch_normalization_40/moving_variance:0': 'backbone.layer3.5.bn1.running_var',
 'resnet50/conv2d_41/kernel:0': 'backbone.layer3.5.conv2.weight',
 'resnet50/batch_normalization_41/gamma:0': 'backbone.layer3.5.bn2.weight',
 'resnet50/batch_normalization_41/beta:0': 'backbone.layer3.5.bn2.bias',
 'resnet50/batch_normalization_41/moving_mean:0': 'backbone.layer3.5.bn2.running_mean',
 'resnet50/batch_normalization_41/moving_variance:0': 'backbone.layer3.5.bn2.running_var',
 'resnet50/conv2d_42/kernel:0': 'backbone.layer3.5.conv3.weight',
 'resnet50/batch_normalization_42/gamma:0': 'backbone.layer3.5.bn3.weight',
 'resnet50/batch_normalization_42/beta:0': 'backbone.layer3.5.bn3.bias',
 'resnet50/batch_normalization_42/moving_mean:0': 'backbone.layer3.5.bn3.running_mean',
 'resnet50/batch_normalization_42/moving_variance:0': 'backbone.layer3.5.bn3.running_var',
 
 # block 4 of the Resnet
 'resnet50/conv2d_43/kernel:0': 'backbone.layer4.0.downsample.0.weight',
 'resnet50/batch_normalization_43/gamma:0': 'backbone.layer4.0.downsample.1.weight',
 'resnet50/batch_normalization_43/beta:0': 'backbone.layer4.0.downsample.1.bias',
 'resnet50/batch_normalization_43/moving_mean:0': 'backbone.layer4.0.downsample.1.running_mean',
 'resnet50/batch_normalization_43/moving_variance:0': 'backbone.layer4.0.downsample.1.running_var',
 'resnet50/conv2d_44/kernel:0': 'backbone.layer4.0.conv1.weight',
 'resnet50/batch_normalization_44/gamma:0': 'backbone.layer4.0.bn1.weight',
 'resnet50/batch_normalization_44/beta:0': 'backbone.layer4.0.bn1.bias',
 'resnet50/batch_normalization_44/moving_mean:0': 'backbone.layer4.0.bn1.running_mean',
 'resnet50/batch_normalization_44/moving_variance:0': 'backbone.layer4.0.bn1.running_var',
 'resnet50/conv2d_45/kernel:0': 'backbone.layer4.0.conv2.weight',
 'resnet50/batch_normalization_45/gamma:0': 'backbone.layer4.0.bn2.weight',
 'resnet50/batch_normalization_45/beta:0': 'backbone.layer4.0.bn2.bias',
 'resnet50/batch_normalization_45/moving_mean:0': 'backbone.layer4.0.bn2.running_mean',
 'resnet50/batch_normalization_45/moving_variance:0': 'backbone.layer4.0.bn2.running_var',
 'resnet50/conv2d_46/kernel:0': 'backbone.layer4.0.conv3.weight',
 'resnet50/batch_normalization_46/gamma:0': 'backbone.layer4.0.bn3.weight',
 'resnet50/batch_normalization_46/beta:0': 'backbone.layer4.0.bn3.bias',
 'resnet50/batch_normalization_46/moving_mean:0': 'backbone.layer4.0.bn3.running_mean',
 'resnet50/batch_normalization_46/moving_variance:0': 'backbone.layer4.0.bn3.running_var',
 
 'resnet50/conv2d_47/kernel:0': 'backbone.layer4.1.conv1.weight',
 'resnet50/batch_normalization_47/gamma:0': 'backbone.layer4.1.bn1.weight',
 'resnet50/batch_normalization_47/beta:0': 'backbone.layer4.1.bn1.bias',
 'resnet50/batch_normalization_47/moving_mean:0': 'backbone.layer4.1.bn1.running_mean',
 'resnet50/batch_normalization_47/moving_variance:0': 'backbone.layer4.1.bn1.running_var',
 'resnet50/conv2d_48/kernel:0': 'backbone.layer4.1.conv2.weight',
 'resnet50/batch_normalization_48/gamma:0': 'backbone.layer4.1.bn2.weight',
 'resnet50/batch_normalization_48/beta:0': 'backbone.layer4.1.bn2.bias',
 'resnet50/batch_normalization_48/moving_mean:0': 'backbone.layer4.1.bn2.running_mean',
 'resnet50/batch_normalization_48/moving_variance:0': 'backbone.layer4.1.bn2.running_var',
 'resnet50/conv2d_49/kernel:0': 'backbone.layer4.1.conv3.weight',
 'resnet50/batch_normalization_49/gamma:0': 'backbone.layer4.1.bn3.weight',
 'resnet50/batch_normalization_49/beta:0': 'backbone.layer4.1.bn3.bias',
 'resnet50/batch_normalization_49/moving_mean:0': 'backbone.layer4.1.bn3.running_mean',
 'resnet50/batch_normalization_49/moving_variance:0': 'backbone.layer4.1.bn3.running_var',
 'resnet50/conv2d_50/kernel:0': 'backbone.layer4.2.conv1.weight',
 'resnet50/batch_normalization_50/gamma:0': 'backbone.layer4.2.bn1.weight',
 'resnet50/batch_normalization_50/beta:0': 'backbone.layer4.2.bn1.bias',
 'resnet50/batch_normalization_50/moving_mean:0': 'backbone.layer4.2.bn1.running_mean',
 'resnet50/batch_normalization_50/moving_variance:0': 'backbone.layer4.2.bn1.running_var',
 'resnet50/conv2d_51/kernel:0': 'backbone.layer4.2.conv2.weight',
 'resnet50/batch_normalization_51/gamma:0': 'backbone.layer4.2.bn2.weight',
 'resnet50/batch_normalization_51/beta:0': 'backbone.layer4.2.bn2.bias',
 'resnet50/batch_normalization_51/moving_mean:0': 'backbone.layer4.2.bn2.running_mean',
 'resnet50/batch_normalization_51/moving_variance:0': 'backbone.layer4.2.bn2.running_var',
 'resnet50/conv2d_52/kernel:0': 'backbone.layer4.2.conv3.weight',
 'resnet50/batch_normalization_52/gamma:0': 'backbone.layer4.2.bn3.weight',
 'resnet50/batch_normalization_52/beta:0': 'backbone.layer4.2.bn3.bias',
 'resnet50/batch_normalization_52/moving_mean:0': 'backbone.layer4.2.bn3.running_mean',
 'resnet50/batch_normalization_52/moving_variance:0': 'backbone.layer4.2.bn3.running_var',
 # fpn part
 'fpn/l2/kernel:0': 'neck.lateral_convs.0.conv.weight',
 'fpn/l2/bias:0': 'neck.lateral_convs.0.conv.bias',
 'fpn/l3/kernel:0': 'neck.lateral_convs.1.conv.weight',
 'fpn/l3/bias:0': 'neck.lateral_convs.1.conv.bias',
 'fpn/l4/kernel:0': 'neck.lateral_convs.2.conv.weight',
 'fpn/l4/bias:0': 'neck.lateral_convs.2.conv.bias',
 'fpn/l5/kernel:0': 'neck.lateral_convs.3.conv.weight',
 'fpn/l5/bias:0': 'neck.lateral_convs.3.conv.bias',
 
 'fpn/post_hoc_d2/kernel:0': 'neck.fpn_convs.0.conv.weight',
 'fpn/post_hoc_d2/bias:0': 'neck.fpn_convs.0.conv.bias',
 'fpn/post_hoc_d3/kernel:0': 'neck.fpn_convs.1.conv.weight',
 'fpn/post_hoc_d3/bias:0': 'neck.fpn_convs.1.conv.bias',
 'fpn/post_hoc_d4/kernel:0': 'neck.fpn_convs.2.conv.weight',
 'fpn/post_hoc_d4/bias:0': 'neck.fpn_convs.2.conv.bias',
 'fpn/post_hoc_d5/kernel:0': 'neck.fpn_convs.3.conv.weight',
 'fpn/post_hoc_d5/bias:0': 'neck.fpn_convs.3.conv.bias',
 'fpn/p6/kernel:0': 'neck.fpn_convs.4.conv.weight',
 'fpn/p6/bias:0': 'neck.fpn_convs.4.conv.bias',
 'fpn/p2-bn/gamma:0': 'neck.extra_bn.0.weight',
 'fpn/p2-bn/beta:0': 'neck.extra_bn.0.bias',
 'fpn/p2-bn/moving_mean:0': 'neck.extra_bn.0.running_mean',
 'fpn/p2-bn/moving_variance:0': 'neck.extra_bn.0.running_var',
 'fpn/p3-bn/gamma:0': 'neck.extra_bn.1.weight',
 'fpn/p3-bn/beta:0': 'neck.extra_bn.1.bias',
 'fpn/p3-bn/moving_mean:0': 'neck.extra_bn.1.running_mean',
 'fpn/p3-bn/moving_variance:0': 'neck.extra_bn.1.running_var',
 'fpn/p4-bn/gamma:0': 'neck.extra_bn.2.weight',
 'fpn/p4-bn/beta:0': 'neck.extra_bn.2.bias',
 'fpn/p4-bn/moving_mean:0': 'neck.extra_bn.2.running_mean',
 'fpn/p4-bn/moving_variance:0': 'neck.extra_bn.2.running_var',
 'fpn/p5-bn/gamma:0': 'neck.extra_bn.3.weight',
 'fpn/p5-bn/beta:0': 'neck.extra_bn.3.bias',
 'fpn/p5-bn/moving_mean:0': 'neck.extra_bn.3.running_mean',
 'fpn/p5-bn/moving_variance:0': 'neck.extra_bn.3.running_var',
 'fpn/p6-bn/gamma:0': 'neck.extra_bn.4.weight',
 'fpn/p6-bn/beta:0': 'neck.extra_bn.4.bias',
 'fpn/p6-bn/moving_mean:0': 'neck.extra_bn.4.running_mean',
 'fpn/p6-bn/moving_variance:0': 'neck.extra_bn.4.running_var',
 
 #rpn part 
 'rpn_head/rpn/kernel:0': 'rpn_head.rpn_conv.0.conv.weight',
 'rpn_head/rpn/bias:0': 'rpn_head.rpn_conv.0.conv.bias',
 'rpn_head/rpn-l2-bn/gamma:0': 'rpn_head.extra_bn.0.weight',
 'rpn_head/rpn-l2-bn/beta:0': 'rpn_head.extra_bn.0.bias',
 'rpn_head/rpn-l2-bn/moving_mean:0': 'rpn_head.extra_bn.0.running_mean',
 'rpn_head/rpn-l2-bn/moving_variance:0': 'rpn_head.extra_bn.0.running_var',
 'rpn_head/rpn-1/kernel:0': 'rpn_head.rpn_conv.1.conv.weight',
 'rpn_head/rpn-1/bias:0': 'rpn_head.rpn_conv.1.conv.bias',
 'rpn_head/rpn-l2-bn-1/gamma:0': 'rpn_head.extra_bn.5.weight',
 'rpn_head/rpn-l2-bn-1/beta:0': 'rpn_head.extra_bn.5.bias',
 'rpn_head/rpn-l2-bn-1/moving_mean:0': 'rpn_head.extra_bn.5.running_mean',
 'rpn_head/rpn-l2-bn-1/moving_variance:0': 'rpn_head.extra_bn.5.running_var',
 'rpn_head/rpn-class/kernel:0': 'rpn_head.rpn_cls.weight',
 'rpn_head/rpn-class/bias:0': 'rpn_head.rpn_cls.bias',
 'rpn_head/rpn-box/kernel:0': 'rpn_head.rpn_reg.weight',
 'rpn_head/rpn-box/bias:0': 'rpn_head.rpn_reg.bias',
 
 'rpn_head/rpn-l3-bn/gamma:0': 'rpn_head.extra_bn.1.weight',
 'rpn_head/rpn-l3-bn/beta:0': 'rpn_head.extra_bn.1.bias',
 'rpn_head/rpn-l3-bn/moving_mean:0': 'rpn_head.extra_bn.1.running_mean',
 'rpn_head/rpn-l3-bn/moving_variance:0': 'rpn_head.extra_bn.1.running_var',
 'rpn_head/rpn-l3-bn-1/gamma:0': 'rpn_head.extra_bn.6.weight',
 'rpn_head/rpn-l3-bn-1/beta:0': 'rpn_head.extra_bn.6.bias',
 'rpn_head/rpn-l3-bn-1/moving_mean:0': 'rpn_head.extra_bn.6.running_mean',
 'rpn_head/rpn-l3-bn-1/moving_variance:0': 'rpn_head.extra_bn.6.running_var',
 
 'rpn_head/rpn-l4-bn/gamma:0': 'rpn_head.extra_bn.2.weight',
 'rpn_head/rpn-l4-bn/beta:0': 'rpn_head.extra_bn.2.bias',
 'rpn_head/rpn-l4-bn/moving_mean:0': 'rpn_head.extra_bn.2.running_mean',
 'rpn_head/rpn-l4-bn/moving_variance:0': 'rpn_head.extra_bn.2.running_var',
 'rpn_head/rpn-l4-bn-1/gamma:0': 'rpn_head.extra_bn.7.weight',
 'rpn_head/rpn-l4-bn-1/beta:0': 'rpn_head.extra_bn.7.bias',
 'rpn_head/rpn-l4-bn-1/moving_mean:0': 'rpn_head.extra_bn.7.running_mean',
 'rpn_head/rpn-l4-bn-1/moving_variance:0': 'rpn_head.extra_bn.7.running_var',
 
 'rpn_head/rpn-l5-bn/gamma:0': 'rpn_head.extra_bn.3.weight',
 'rpn_head/rpn-l5-bn/beta:0': 'rpn_head.extra_bn.3.bias',
 'rpn_head/rpn-l5-bn/moving_mean:0': 'rpn_head.extra_bn.3.running_mean',
 'rpn_head/rpn-l5-bn/moving_variance:0': 'rpn_head.extra_bn.3.running_var',
 'rpn_head/rpn-l5-bn-1/gamma:0': 'rpn_head.extra_bn.8.weight',
 'rpn_head/rpn-l5-bn-1/beta:0': 'rpn_head.extra_bn.8.bias',
 'rpn_head/rpn-l5-bn-1/moving_mean:0': 'rpn_head.extra_bn.8.running_mean',
 'rpn_head/rpn-l5-bn-1/moving_variance:0': 'rpn_head.extra_bn.8.running_var',
 
 'rpn_head/rpn-l6-bn/gamma:0': 'rpn_head.extra_bn.4.weight',
 'rpn_head/rpn-l6-bn/beta:0': 'rpn_head.extra_bn.4.bias',
 'rpn_head/rpn-l6-bn/moving_mean:0': 'rpn_head.extra_bn.4.running_mean',
 'rpn_head/rpn-l6-bn/moving_variance:0': 'rpn_head.extra_bn.4.running_var',
 'rpn_head/rpn-l6-bn-1/gamma:0': 'rpn_head.extra_bn.9.weight',
 'rpn_head/rpn-l6-bn-1/beta:0': 'rpn_head.extra_bn.9.bias',
 'rpn_head/rpn-l6-bn-1/moving_mean:0': 'rpn_head.extra_bn.9.running_mean',
 'rpn_head/rpn-l6-bn-1/moving_variance:0': 'rpn_head.extra_bn.9.running_var',}

original_name_list = []
new_name_list = []

for ele in params_name_conversion:
    original_name_list.append(ele)
    new_name_list.append(params_name_conversion[ele])
    
print(len(original_name_list), len(new_name_list), len(list(set(original_name_list))), len(list(set(new_name_list))))
    

'''
import torch
from collections import OrderedDict

original_model = torch.load('/home/zhuoming/resnet50_vild_original_name.pth')


new_state_dict = OrderedDict()
for name in params_name_conversion:
    new_name = params_name_conversion[name]
    original_value = original_model[name]
    if len(original_value.shape) > 1:
        new_value = original_value.permute(3,2,1,0)
        #print(original_value.shape, new_value.shape)
    else:
        new_value = original_value
    new_state_dict[new_name] = new_value
    print(original_value.shape, new_value.shape)
    

result_name = '/data/zhuoming/detection/pretrained/vild_rpn.pth'

torch.save(new_state_dict, result_name)'''