_base_ = './cls_finetuner_clip_full_coco.py'

# change the classification loss
# add the text encoder module
# fixed the all parametere except the ln of the text encoder
model = dict(
    rpn_head=dict(
        cate_names=['person', 'bicycle', 'car', 'motorcycle', 'airplane', 
            'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 
            'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 
            'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 
            'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 
            'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 
            'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 
            'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 
            'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 
            'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 
            'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 
            'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 
            'hair drier', 'toothbrush'],
        test_with_attribute=True,
        # the test with make use of the attributes for each class
        # and combine the predicted scores of its attributes as
        # the final prediction for the cate
        cate_attribute=dict(
            person=['arm', 'leg', 'hand', 'head'],
            bicycle=['bicycle on the ground'],
            car=['car on the highway', 'car on the road', 'car in the parking lot', 
                'SUV', 'SUV on the highway', 'SUV on the road', 'SUV in the parking lot'],
            motorcycle=['motorcycle on the highway', 'motorcycle on the road'],
            airplane=['airplane in the sky'],
            bus=['school bus'],
            train=['train on the rails'],
            truck=['truck on the highway', 'truck on the road', 'truck in the parking lot'],
            boat=['boat on the river'],
            traffic_light=['traffic light on the road'],
            fire_hydrant=['red firehydrant'],
            stop_sign=['red stop sign'],
            parking_meter=['parking meter on the roadside'],
            bench=['bench in the park', 'bench on the roadside'],
            bird=['brid in the sky', 'bird on the tree branch', 'bird in the cage', 'bird on the ground'],
            cat=['ragdoll', 'maine coon'],
            dog=['chihuahua', 'bulldog', 'golden retriever', 'husky', 'border collie'],
            horse=['horse on the grass'],
            sheep=['sheep on the grass'],
            cow=['cow on the grass'],
            elephant=['elephant with long nose'],
            bear=['brown bear', 'polar bear'],
            zebra=['horse with stripes'],
            giraffe=['giraffe with long neck'],
            backpack=['black backpack'],
            umbrella=['black umbrella'],
            handbag=['red handbag', 'black handbag'],
            tie=['bow tie'],
            suitcase=[],
            frisbee=[],
            skis=[],
            snowboard=[],
            sports_ball=['basketball', 'baseball', 'football', 'soccer', 'baseball'],
            kite=['kite in the sky'],
            baseball_bat=[],
            baseball_glove=[],
            skateboard=[],
            surfboard=[],
            tennis_racket=[],
            bottle=[],
            wine_glass=[],
            cup=[],
            fork=[],
            knife=[],
            spoon=[],
            bowl=[],
            banana=['yellow banana'],
            apple=['red apple', 'green apple'],
            sandwich=['sandwich on the plate'],
            orange=[],
            broccoli=['green broccoli'],
            carrot=['red carrot'],
            hot_dog=['hot dog on the plate'],
            pizza=['pizza on the plate'],
            donut=['donut on the plate'],
            cake=['cake on the plate'],
            chair=['chair on the ground', 'chair in the living room'],
            couch=['couch in the living room'],
            potted_plant=['green potted plant'],
            bed=['bed in the bedroom'],
            dining_table=['dining table in the kitchen'],
            toilet=[],
            tv=['tv on the wall', 'tv on the desk'],
            laptop=['laptop on the desk'],
            mouse=['mouse on the desk'],
            remote=['remote on the desk'],
            keyboard=['keyboard on the desk'],
            cell_phone=['phone'],
            microwave=['microwave in the kitchen'],
            oven=['oven in the kitchen'],
            toaster=['toaster in the kitchen'],
            sink=['sink in the kitchen'],
            refrigerator=['refrigerator in the kitchen'],
            book=['book on the bookshelf'],
            clock=['wall clock', 'clock on the wall'],
            vase=['vase in the living room', 'vase on the ground'],
            scissors=['scissors on the table'],
            teddy_bear=['teddy bear on the ground', 'toy'],
            hair_drier=[],
            toothbrush=[]
            )
        )
    )