_base_ = './cls_finetuner_clip_full_coco.py'

# change the classification loss
# add the text encoder module
# fixed the all parametere except the ln of the text encoder
model = dict(
    rpn_head=dict(
        cate_names=['person', 'bicycle', 'car', 'motorcycle', 'airplane', 
            'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 
            'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 
            'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 
            'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 
            'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 
            'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 
            'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 
            'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 
            'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 
            'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 
            'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 
            'hair drier', 'toothbrush'],
        test_with_attribute=True,
        # the test with make use of the attributes for each class
        # and combine the predicted scores of its attributes as
        # the final prediction for the cate
        cate_attribute=dict(
            person=[],
            bicycle=[],
            car=[],
            motorcycle=[],
            airplane=['aircraft', 'airliner', 'plane', 'jet'],
            bus=[],
            train=['caravan', 'convoy', 'line', 'concatenation'],
            truck=['crate', 'freighter', 'lorry', 'wheels'],
            boat=['barge', 'canoe', 'carft', 'ship'],
            traffic_light=['red light', 'stoplight', 'yellow light', 'green light'],
            fire_hydrant=[],
            stop_sign=[],
            parking_meter=[],
            bench=[],
            bird=[],
            cat=[],
            dog=[],
            horse=[],
            sheep=[],
            cow=[],
            elephant=[],
            bear=[],
            zebra=[],
            giraffe=[],
            backpack=[],
            umbrella=[],
            handbag=[],
            tie=[],
            suitcase=[],
            frisbee=[],
            skis=[],
            snowboard=[],
            sports_ball=[],
            kite=[],
            baseball_bat=[],
            baseball_glove=[],
            skateboard=[],
            surfboard=[],
            tennis_racket=[],
            bottle=[],
            wine_glass=[],
            cup=[],
            fork=[],
            knife=[],
            spoon=[],
            bowl=[],
            banana=[],
            apple=[],
            sandwich=[],
            orange=[],
            broccoli=[],
            carrot=[],
            hot_dog=[],
            pizza=[],
            donut=[],
            cake=[],
            chair=[],
            couch=[],
            potted_plant=[],
            bed=[],
            dining_table=[],
            toilet=[],
            tv=[],
            laptop=[],
            mouse=[],
            remote=[],
            keyboard=[],
            cell_phone=[],
            microwave=[],
            oven=[],
            toaster=[],
            sink=[],
            refrigerator=[],
            book=[],
            clock=[],
            vase=[],
            scissors=[],
            teddy_bear=[],
            hair_drier=[],
            toothbrush=[]
            )
        )
    )